//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuSignSample.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Keys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Keys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocuSignSample.resources.Keys", typeof(Keys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountID.
        /// </summary>
        public static string AccountId {
            get {
                return ResourceManager.GetString("AccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addsigs.
        /// </summary>
        public static string AddSigs {
            get {
                return ResourceManager.GetString("AddSigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIAccountID.
        /// </summary>
        public static string ApiAccountId {
            get {
                return ResourceManager.GetString("ApiAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIAccounts.
        /// </summary>
        public static string ApiAccounts {
            get {
                return ResourceManager.GetString("ApiAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIEmail.
        /// </summary>
        public static string ApiEmail {
            get {
                return ResourceManager.GetString("ApiEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIIKey.
        /// </summary>
        public static string ApiIkey {
            get {
                return ResourceManager.GetString("ApiIkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIPassword.
        /// </summary>
        public static string ApiPassword {
            get {
                return ResourceManager.GetString("ApiPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIServiceSoap.
        /// </summary>
        public static string ApiServiceSoap {
            get {
                return ResourceManager.GetString("ApiServiceSoap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIUrl.
        /// </summary>
        public static string ApiUrl {
            get {
                return ResourceManager.GetString("ApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIUserEmail.
        /// </summary>
        public static string ApiUserEmail {
            get {
                return ResourceManager.GetString("ApiUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIUserID.
        /// </summary>
        public static string ApiUserId {
            get {
                return ResourceManager.GetString("ApiUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIUserName.
        /// </summary>
        public static string ApiUsername {
            get {
                return ResourceManager.GetString("ApiUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collabfields.
        /// </summary>
        public static string CollabFields {
            get {
                return ResourceManager.GetString("CollabFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conditionalfields.
        /// </summary>
        public static string ConditionalFields {
            get {
                return ResourceManager.GetString("ConditionalFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevCenterEmail.
        /// </summary>
        public static string DevCenterEmail {
            get {
                return ResourceManager.GetString("DevCenterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevCenterIKey.
        /// </summary>
        public static string DevCenterKey {
            get {
                return ResourceManager.GetString("DevCenterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevCenterName.
        /// </summary>
        public static string DevCenterName {
            get {
                return ResourceManager.GetString("DevCenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevCenterPassword.
        /// </summary>
        public static string DevCenterPassword {
            get {
                return ResourceManager.GetString("DevCenterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditFirst.
        /// </summary>
        public static string EditFirst {
            get {
                return ResourceManager.GetString("EditFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emailBlurb.
        /// </summary>
        public static string EmailBlurb {
            get {
                return ResourceManager.GetString("EmailBlurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enablepaper.
        /// </summary>
        public static string EnablePaper {
            get {
                return ResourceManager.GetString("EnablePaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnvelopeID.
        /// </summary>
        public static string EnvelopeId {
            get {
                return ResourceManager.GetString("EnvelopeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnvelopeIDs.
        /// </summary>
        public static string EnvelopeIds {
            get {
                return ResourceManager.GetString("EnvelopeIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnvelopeStatus.
        /// </summary>
        public static string EnvelopeStatus {
            get {
                return ResourceManager.GetString("EnvelopeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to errorMessage.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expiration.
        /// </summary>
        public static string Expiration {
            get {
                return ResourceManager.GetString("Expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formfields.
        /// </summary>
        public static string FormFields {
            get {
                return ResourceManager.GetString("FormFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        public static string Id_Lower {
            get {
                return ResourceManager.GetString("Id_Lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntegratorsKey.
        /// </summary>
        public static string IntegratorsKey {
            get {
                return ResourceManager.GetString("IntegratorsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to markup.
        /// </summary>
        public static string Markup {
            get {
                return ResourceManager.GetString("Markup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneSigner.
        /// </summary>
        public static string OneSigner {
            get {
                return ResourceManager.GetString("OneSigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecipientEmail.
        /// </summary>
        public static string RecipientEmail {
            get {
                return ResourceManager.GetString("RecipientEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecipientInvite.
        /// </summary>
        public static string RecipientInvite {
            get {
                return ResourceManager.GetString("RecipientInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecipientInviteToggle
        ///.
        /// </summary>
        public static string RecipientInviteToggle {
            get {
                return ResourceManager.GetString("RecipientInviteToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecipientName.
        /// </summary>
        public static string RecipientName {
            get {
                return ResourceManager.GetString("RecipientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecipientRole.
        /// </summary>
        public static string RecipientRole {
            get {
                return ResourceManager.GetString("RecipientRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecipientSecurity.
        /// </summary>
        public static string RecipientSecurity {
            get {
                return ResourceManager.GetString("RecipientSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecipientSecuritySetting.
        /// </summary>
        public static string RecipientSecuritySetting {
            get {
                return ResourceManager.GetString("RecipientSecuritySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reminders.
        /// </summary>
        public static string Reminders {
            get {
                return ResourceManager.GetString("Reminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendNow.
        /// </summary>
        public static string SendNow {
            get {
                return ResourceManager.GetString("SendNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signerattachment.
        /// </summary>
        public static string SignerAttachment {
            get {
                return ResourceManager.GetString("SignerAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to src.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stockdoc.
        /// </summary>
        public static string StockDoc {
            get {
                return ResourceManager.GetString("StockDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwoSigners.
        /// </summary>
        public static string TwoSigners {
            get {
                return ResourceManager.GetString("TwoSigners", resourceCulture);
            }
        }
    }
}
