source 'http://rubygems.org'

ruby "1.9.3"

gem 'rails', '4.2.5'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'


gem 'soap4r', :git => 'git://github.com/docusign/soap4r.git'
gem 'docusignsdk', :git => 'git://github.com/market-art/docusignsdk.git'
gem 'intercession', '=2.0.0'
gem 'httpclient', '=2.1.6.1'
gem 'sqlite3'

gem 'activerecord-session_store'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
